Repository dkpro/dkpro-cassis, pull requests merged in 2021-12, with the labels that each got.

#239 #238 - Error parsing FSList in cTAKES xmi
  cassis/cas.py
  cassis/typesystem.py
  cassis/xmi.py
  tests/fixtures.py
  tests/test_files/typesystems/typesystem_with_list_features.xml
  tests/test_files/xmi/cas_with_list_features.xmi
  tests/test_xmi.py
Labels: 🐛Bug

#169 #168 - Experimental JSON CAS support
  .gitignore
  Makefile
  README.rst
  cassis/__init__.py
  cassis/cas.py
  cassis/json.py
  cassis/typesystem.py
  cassis/xmi.py
  tests/performance.py
  tests/test_files/json/README.md
  tests/test_files/json/fs_as_array/ser-ref/casWithEmojiUnicodeTextAndAnnotations/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithEmojiUnicodeTextAndAnnotations/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithEmojiUnicodeTextAndAnnotations/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/casWithFloatingPointSpecialValues/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithFloatingPointSpecialValues/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithFloatingPointSpecialValues/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/casWithFloatingPointSpecialValues/typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithLeftToRightTextAndAnnotations/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithLeftToRightTextAndAnnotations/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithLeftToRightTextAndAnnotations/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/casWithSofaDataArray/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithSofaDataArray/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithSofaDataArray/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/casWithSofaDataURI/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithSofaDataURI/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithSofaDataURI/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/casWithText/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithText/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithText/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/casWithTextAndAnnotations/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithTextAndAnnotations/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithTextAndAnnotations/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/casWithTraditionalChineseTextAndAnnotations/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithTraditionalChineseTextAndAnnotations/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithTraditionalChineseTextAndAnnotations/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/casWithoutTextButWithAnnotations/data.json
  tests/test_files/json/fs_as_array/ser-ref/casWithoutTextButWithAnnotations/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/casWithoutTextButWithAnnotations/debug.xmi
  tests/test_files/json/fs_as_array/ser-ref/emptyCas/data.json
  tests/test_files/json/fs_as_array/ser-ref/emptyCas/debug-typesystem.xml
  tests/test_files/json/fs_as_array/ser-ref/emptyCas/debug.xmi
  tests/test_json.py
  tests/test_xmi.py
  tests/util.py
Labels: 🆕Enhancement, Module: Json

#243 #242 - Array features are wrapped in extra array
  cassis/cas.py
  cassis/typesystem.py
  cassis/xmi.py
  tests/fixtures.py
  tests/test_files/typesystems/typesystem_with_array_features.xml
  tests/test_files/xmi/cas_with_array_features.xmi
  tests/test_xmi.py
Labels: 🐛Bug

#245 #244 - Update dependencies
  setup.py
Labels: ⚙️Refactoring

#246 #162 - Handling of Invalid sofa indexes
  cassis/cas.py
  cassis/json.py
  cassis/xmi.py
  tests/test_xmi.py
Labels: 🐛Bug
